datosgobar/django-datajsonar

django_datajsonar/apps/api/admin.py
=> Agrego titulo del dataset al admin

django_datajsonar/apps/management/management/commands/_utils.py, django_datajsonar/apps/management/management/commands/schedule_indexation.py, django_datajsonar/apps/management/tests/scheduler_tests.py, django_datajsonar/libs/indexing/tasks.py
Closes #2 
Agrega un management command para crear RepeatableJobs que generen nuevos ReadDataJsonTasks.
=> 2 automatizar creacion de read datajson tasks

.gitignore, requirements/base.txt
=> Permito que la version de requests sea mas abierta

requirements/base.txt
=> Permito que la version de django sea entre 1.11.6 y menor a 2.0.0

django_datajsonar/apps/api/admin.py
Agrego la función `get_title` al `list_display` de Datasets y cambio el fallback que tenía.
=> Mostrar title en modelos de dataset

django_datajsonar/indexing/catalog_reader.py, django_datajsonar/indexing/database_loader.py, django_datajsonar/indexing/tests/loader_tests.py, django_datajsonar/indexing/utils.py
Cuando busca el modelo para marcarlo con error, incluye con qué modelo está relacionado en la jerarquía (dataset con catálogo, distribución con dataset y field con distribución) para desambiguar.
=> Log exception bugfix

django_datajsonar/models.py
Agrego metodo `__str__()` a varios modelos para uso con py3
=> verbose names

django_datajsonar/admin.py, django_datajsonar/utils.py
Closes datosgobar/monitoreo-apertura#61
Agrega un action en el admin de dataset para descargar los datasets indexables selecionados.
=> Agrego el action para generar los csv

django_datajsonar/admin.py, django_datajsonar/tests/dataset_indexing_tests.py, django_datajsonar/utils.py, django_datajsonar/views.py
Closes datosgobar/monitoreo-apertura#60
Implementa la view `admin/django_datajson/dataset/federacion-config.csv` que descarga un csv con todos datasets marcados como indexables
=> Generar config files view

django_datajsonar/tests/dataset_indexing_tests.py, django_datajsonar/utils.py, django_datajsonar/views.py
Closes #77
Closes #78
Permite descargar el config file sin la necesidad de loguearse y saca la hora del nombre del archivo
=> 77 78 cambios a la descarga de csv

django_datajsonar/tasks.py, django_datajsonar/tests/tasks_tests.py
Agrega 2 wrappers para poder encolar el repeatablejob de 2 modos distintos
=> Schedule rdt wrappers

conf/settings/base.py, django_datajsonar/admin.py, django_datajsonar/management/commands/schedule_default_processes.py, django_datajsonar/tests/synchro_tests.py
- Agrega la posibilidad de definir synchronizers y stages en settings.py y levantarlos con un mangement command.
- Agrega tests del comportamiento.
=> Default processes

django_datajsonar/indexing/catalog_reader.py
=> fuerzo la lectura de formatos a partir de la metadata

django_datajsonar/management/commands/schedule_upkeep_job.py, django_datajsonar/migrations/ensure_upkeep_job_exists.py, django_datajsonar/tests/scheduler_tests.py
Implementa un management command para crear y schedulear un trabajo upkeep para el  funcionamiento del synchronizer
=> 80 schedule upkeep job

django_datajsonar/admin/synchronizer.py, django_datajsonar/admin/tasks.py, django_datajsonar/forms.py
Unifica comportamiento de programación de tareas, ahora ambas acciones utilizan el backend provisto por Synchronizers.
=> Schedule task usa UI de Synchronizer

django_datajsonar/tests/metadata_generator_tests.py, django_datajsonar/urls.py, django_datajsonar/utils/metadata_csv_writer.py, django_datajsonar/utils/translations.py, django_datajsonar/utils/utils.py, django_datajsonar/views.py
Closes #135 #92 
- Agrega 2 views para descargar la metadata conseguida a partir del issue #134.
- Agrega tests para las transformaciones que se aplican a esa metadata
=> 135 nodes metadata csv

django_datajsonar/tests/metadata_generator_tests.py, django_datajsonar/urls.py, django_datajsonar/utils/download_response_writer.py, django_datajsonar/utils/metadata_writer.py, django_datajsonar/utils/utils.py, django_datajsonar/views.py, requirements/base.txt
Closes #177
- Agrega las views y urls para descargar `nodos.xlsx` y `nodes.xlsx`
- Extrae la funcionalidad para escribir metadata
=> 177 node metadata xlsx download

django_datajsonar/admin/manual_synchronizer_view.py, django_datajsonar/admin/synchronizer.py, django_datajsonar/forms/manual_synchronizer_form.py, django_datajsonar/tests/admin_tests/synchronizer_admin_tests.py
=> Permito correr synchronizers manualmente sobre todos los nodos

django_datajsonar/admin/data_json.py, django_datajsonar/static/django_datajsonar/css/dataset.css
Closes datosgobar/monitoreo-apertura#208
Antes:
Después
=> Modifico columnas del DatasetAdmin para tener columnas menos anchas

django_datajsonar/models/node.py, django_datajsonar/tests/node_tests.py, requirements/testing.txt
Creo nuevo metodo en la clase Nodo para la lectura de catalogos (devuelve la data con pydatajson)
Closes #154
=> Creo nuevo metodo de Nodo para leer catalogos. Agrego test

django_datajsonar/models/node.py, django_datajsonar/tests/utils_tests/catalog_file_generator_tests.py, django_datajsonar/urls.py, django_datajsonar/utils/catalog_file_generator.py, django_datajsonar/views.py
- Creo views para servir los archivos creados en formato JSON y XLSX de cada Nodo.
- Creo urls para descargar los archivos a través de dichas views.
- Corrijo path donde se guardan los archivos de un Nodo.
- Agrego test
Closes #171
=> Publicar catalogos en formato JSON y XLSX
