datosgobar/django-datajsonar

README.md, django_datajsonar/apps/management/management/commands/_utils.py, django_datajsonar/apps/management/management/commands/schedule_indexation.py, django_datajsonar/apps/management/management/commands/schedule_task_finisher.py, django_datajsonar/apps/management/tests/scheduler_tests.py, django_datajsonar/libs/indexing/tasks.py
Closes #3 
Agrega el comando `schedule_task_finisher`, en esencia es igual al `schedule_indexation` con la diferencia en nombre y que define otros valores de default.
=> 3 automatizar cierre de read datajson tasks

django_datajsonar/apps/management/actions.py, django_datajsonar/apps/management/tasks.py, django_datajsonar/libs/indexing/catalog_reader.py
Por el momento, solo leer los catálogos con formato json. Atrapar excepción en `index_catalog()` y seguir con la indexacion de los nodos y generar los ids de distribuciones en caso de que no esten presentes.
=> Robustecer el manejo de tareas de management

django_datajsonar/apps/management/actions.py, django_datajsonar/apps/management/admin.py, django_datajsonar/apps/management/tasks.py
La acción de procesar un nodo se hace asincronicamente al llamar a `process_node_register_file_action()`. Además saca la dependencia de un campo `dataset_identifier` en las distribuciones.
=> Procesar asincronicamente los nodos

django_datajsonar/libs/indexing/catalog_reader.py, django_datajsonar/libs/indexing/tests/reader_tests.py, django_datajsonar/libs/indexing/tests/samples/mixed_time_series_catalog.json
Si está seteado `DATAJSON_AR_TIME_SERIES_ONLY` en settings, se filtran los datasets por ese parámetro (en la llamada `get_datasets`). Si no lo está se asume un valor `False`.
=> Agrego parámetro de config para indexar solo series de tiempo

django_datajsonar/actions.py, django_datajsonar/strings.py, django_datajsonar/tests/dataset_indexing_tests.py, django_datajsonar/tests/samples/test_missing_catalog.csv
Durante el `bulk_whitelist()`, en caso de no encontrarse el catalogo indicado por id, marca el error en los logs del DatasetIndexingFile y continua con la ejecución.
=> 35 robustecer bulk whitelist

django_datajsonar/indexing/database_loader.py, django_datajsonar/indexing/tests/loader_tests.py
Filtra las distribuciones si tienen o no series de tiempo dependiendo del valor de verdad de `DATAJSON_AR_TIME_SERIES_ONLY`
=> Fix time series only

django_datajsonar/indexing/catalog_reader.py, django_datajsonar/indexing/tests/reader_tests.py
Closes datosgobar/monitoreo-apertura#59
Cambia el orden en que se realizaban las operaciones para dejar en falso el campo `updated`.
Marca con `error` y pone `present` en falso en caso de que ocurra una excepción bajando el datajson.
=> Catalogos ausentes sin conexion

django_datajsonar/admin.py
Mueve (y mejora) la config del admin de ReadDataJsonTask a un modelo usable de manera abstracta por cualquier modelo de django que herede de AbstractTask, que valida que no se puedan correr dos tareas al mismo tiempo
=> Agrego config de admin para AbstractTask

django_datajsonar/admin.py, django_datajsonar/models.py, django_datajsonar/static/django_datajsonar/css/hide_title.css
Agregar un `TabularInlineModelAdmin` para mostrar los metadatos enriquecidos de cada entidad en el admin.
=> Metadatos enriquecidos en el admin

conf/settings/base.py, django_datajsonar/admin.py, django_datajsonar/forms.py, django_datajsonar/management/commands/schedule_default_tasks.py, django_datajsonar/templates/change_list.html, django_datajsonar/templates/scheduler.html, django_datajsonar/tests/scheduler_tests.py, django_datajsonar/views.py, docs/uso.md
Closes #51 
- Agrega un formulario para programar `RepeatableJobs` más fácilmente. Si el task tiene un atributo `callable_str`, llena el campo automáticamente con este en un readonly field. En otro caso, pide el callable.
- Agrega un management command para programar `RepeatableJobs` definidos en los settings de la aplicación.
- Agrega tests del management command.
- Agrega documentación.
=> Abstract tasks scheduling

django_datajsonar/models.py, docs/uso.md
Si `storage` vale `None` django por default agarra el default storage (que estamos usando actualmente)
=> Parametrizo el storage de las distribuciones

django_datajsonar/admin.py, django_datajsonar/templates/change_list.html, django_datajsonar/templates/scheduler.html
Agrega la información de la aplicación y el nombre del modelo al nombre de la url con el mismo esquema que usa el admin de django.
=> desambiguo la resolucion de urls de schedule_task

django_datajsonar/models.py
Paso a guardarlos bajo
distribution_raw/{catalog_identifier}/{distribution_identifier}.csv para
evitar problemas distribuciones con mismo identifier de distintos
catálogos pisando sus archivos de distribuciones entre sí
Closes #76
=> Cambio el directorio de archivos de distribuciones

django_datajsonar/models.py, django_datajsonar/tasks.py, django_datajsonar/tests/synchro_tests.py
Se agrega una validación para que el callable_str de los stage
referencien a métodos asincrónicos de rq, chequeando por la existencia
del atributo 'delay', y llamándolo al ejecutarse el stage. Con este
cambio obtenemos una garantía que los stage programados no van a trabar
la acción de upkeep, que debe poder ejecutarse frecuentemente.
=> Fuerzo las tareas de stages a ser async

django_datajsonar/admin.py, django_datajsonar/templates/synchro_change_list.html, django_datajsonar/templates/synchronizer.html
La view custom de "create process" pasa a reemplazar la vista default
del admin, add_view. Esto hace que todos los botones del admin de crear
un nuevo modelo pasen a mostrar la vista de nuevo proceso, que también
maneja la creación de los stages.
=> Unifico views del admin de Synchronizer

django_datajsonar/indexing/database_loader.py
Por alguna razón estabamos leyendo el archivo como UTF-8 y luego pasandolo a bytes, mejor leamos bytes directamente. Evita problemas cuando el archivo está en latin-1
=> Evito encoding en utf8

django_datajsonar/tests/distribution_metadata_generator_tests.py, django_datajsonar/tests/samples/sample_data.json, django_datajsonar/urls.py, django_datajsonar/utils/download_response_writer.py, django_datajsonar/utils/metadata_generator.py, django_datajsonar/utils/translations.py, django_datajsonar/views.py
Closes datosgobar/monitoreo-apertura#178
- Agrega al csv los campos que se leen de la metadata de cada modelo
- Agrega tests del comportamiento
(Además, le pone name a las urls de descarga de archivos. Por un tema de buenas prácticas para poder hacer `reverse()` cuando haga falta)
=> 178 distribuciones full metadata

django_datajsonar/indexing/tests/reader_tests.py, django_datajsonar/tests/distribution_metadata_generator_tests.py, django_datajsonar/tests/samples/another_catalog.json, django_datajsonar/utils/metadata_generator.py, manage.py
- Agrego orden a las filas del `distribuciones.csv` según los valores de las columnas `catalogo_id`, `dataset_id` y `distribucion_id`, en forma alfabética ascendente
- Creo tests para verificar el orden
Closes #147
=> 147 ordenar filas distribuciones csv

django_datajsonar/tests/distribution_metadata_generator_tests.py, django_datajsonar/utils/metadata_generator.py, django_datajsonar/utils/translations.py
- Agrego campo `distribucion_descripcion` a los archivos distribuciones.csv, ya que este no existía. Lo ubiqué en donde la descripción del issue especificaba
- Elimino una aserción duplicada de un test
- Agrego aserción para verificar que se esté guardando bien la descripción en el .csv
Closes #149
=> Agrego campo de distribucion_descripcion a los CSV, en el orden correspondiente

conf/settings/base.py, django_datajsonar/admin/data_json.py
* list_select_related = True para evitar el fetch de datasets/distribuciones reptidas en la change list
* Marco entidad procedente como readonly para evitar fetch de todas las distribuciones posibles en cada acceso a detalle de field
Closes #137
=>  Optimización de vistas del admin

django_datajsonar/indexing/tests/loader_tests.py
=> El tamaño del archivo (byteSize) se guarda en distribution.data_file.size

django_datajsonar/admin/synchronizer.py, django_datajsonar/tests/admin_tests/synchronizer_admin_tests.py
Closes #169 
Bugfix a synchronizers con id mayor a 9 haciendose imposibles de editar.
=> Corrijo URL de synchronizers

django_datajsonar/tests/view_tests.py, django_datajsonar/views.py
- Los archivos de catálogos para los nodos en formato JSON ahora se muestran en el browser y no como attachment
Closes #178
=> Catálogos en JSON se muestran en browser

django_datajsonar/tests/utils_tests/catalog_file_generator_tests.py, django_datajsonar/utils/catalog_file_generator.py
No especificar el formato del catalogo a DataJson causaba que pueda tirar una excepcion si el url no tenia un formato especifico.
=> Fuerzo formato en la creación del Datajson para la creación de archivos

conf/settings/base.py, django_datajsonar/admin/restore_default_synchronizers_view.py, django_datajsonar/strings.py
- Agrega la posibilidad de definir `week_days` en la configuración default de synchronizers
=> funcionalidad para definir días en los synchronizers default

django_datajsonar/tests/catalog_reader_tests.py, django_datajsonar/utils/catalog_file_generator.py
Closes #186 
En una lectura de catalogos, cuando se descargan catalogos por url en la creacion de archivos de un nodo, ahora se verifica o no el certificado ssl segun el campo del nodo
=> Verificacion ssl en creacion de archivos
